name: Deploy to Server

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy places app
    runs-on: self-hosted
    
    steps:
      - name: Deploy places
        run: |
          /home/sheldon/scripts/deploy-app.sh places
